language: node_js
node_js:
- '5'
- '6'
- '7'
install:
- npm install
before_script:
- npm run lint
- npm run build
script:
- npm test
after_script:
- npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: "tlaziuk@gmail.com"
  api_key:
    secure: j4shhcLyo1tNvvZX6r/mQq4Z7tm6QIxULBKy7vKYpzitHrapiBo1RgxNkskD6qlaeCUJ+JWdM11WL76soETBitGi8OkMUCl6ysei34iQXleXDrI3YylUMkohrlLs+CrXA8hJWUUmjJ+HVFIrlVRjUSIKaClmhEBer0BDFmJ8I8A5ID+fEnMnJsiaZXfo20jrv6TVKr7XY8LUd12X5UziuDJUskXC/BtlypfNkK1BiWiKW8/elPVeZZVfafwrqST4wC96SK0LxrpBJ2ioKkEeyVMOHx4b1UA9Z2DQi04QdGXq6CTZVBm9xPche4LusbBdt3pTBscgoumftbNSWWKWGFvSsjctDa0JKfqqzwMjxieG+OFYtHSuVK1o/eBrOrQbD75/CTxBhnUHYqgkfLOPMXSJWGjZMKmRpXpc5mf/KN+px9gyDElK7Ya3hFcJXnMl1mKu8sKV4GYgYMRJl6Dbo8pDeJNgEDCYfuIqc8YZcx2T5GFD+qge6jKBBruy9b6Q8K4Uyd1cmwGP3F1mrNU1EVXNg/7h91SqAlwNtrUPt6tS6smP2ZEOIoeR437gI4SE3pdQXzQlKTvjoP1UmUKe4NbHgjKmpZTTGQh9nPJAG0mKz5SKgiCTdf8HOaDq6reEymn0spQfAll0VxiE2EPC3MkrG/do+6mIqTztz6AQBLM=
  on:
    tags: true
    repo: tlaziuk/carouselic
